name: Build

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tags:
        - cxx-Alpine
        # - cxx-CentOS6 # CentOS 6 is EOL, so this image does not need to be rebuilt each time
        - cxx-Trusty
        - cxx-Xenial
        - nifty_pascal-linux
        - cxx-extras-Alpine
        - packaging-utils-Alpine
        - python-latex-Alpine

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build ${{ matrix.tags }} --tag 76eddge/build-images:${{ matrix.tags }} --target deploy
      env:
        DOCKER_BUILDKIT: 1

    - name: Login to DockerHub
      if: github.event_name == 'release'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: github.event_name == 'release'
      run: docker push -a 76eddge/build-images

    - name: Run Grype Scan
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/bin
        grype -o sarif '76eddge/build-images:${{ matrix.tags }}' > ${{ matrix.tags }}.sarif

    - name: Upload Grype Scan Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ matrix.tags }}.sarif
        category: ${{ matrix.tags }}

  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        net stop docker
        dockerd --unregister-service
        dockerd --register-service --storage-opt "size=40G"
        net start docker
        cp nifty_pascal-linux/build.gradle nifty_pascal-windows/
        docker build nifty_pascal-windows --tag 76eddge/build-images:nifty_pascal-windows

    - name: Login to DockerHub
      if: github.event_name == 'release'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: github.event_name == 'release'
      run: docker push -a 76eddge/build-images

    - name: Run Grype Scan
      run: |
        choco install grype
        grype -o sarif '76eddge/build-images:nifty_pascal-windows' | Out-File nifty_pascal-windows.sarif utf8

    - name: Upload Grype Scan Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: nifty_pascal-windows.sarif
        category: nifty_pascal-windows
