name: Build

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        tags:
        - cxx-Alpine
        # - cxx-CentOS6 # CentOS 6 is EOL, so this image does not need to be rebuilt each time
        - cxx-Trusty
        - cxx-Xenial

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build ${{ matrix.tags }} --tag 76eddge/build-images:${{ matrix.tags }} --target deploy
      env:
        DOCKER_BUILDKIT: 1

    - id: anchore-scan
      name: Run Anchore Scan
      uses: anchore/scan-action@v3
      with:
        image: '76eddge/build-images:${{ matrix.tags }}'

    - name: Store Anchore Scan Results
      run: |
        mkdir -p scan-results
        cp ${{ steps.anchore-scan.outputs.sarif }} scan-results/${{ matrix.tags }}.sarif

    - name: Upload Anchore Scan Report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: scan-results/${{ matrix.tags }}.sarif

    - name: Login to DockerHub
      if: github.event_name == 'release'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: github.event_name == 'release'
      run: docker push -a 76eddge/build-images

  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        net stop docker
        dockerd --unregister-service
        dockerd --register-service --storage-opt "size=40G"
        net start docker
        docker build nifty_pascal-windows --tag 76eddge/build-images:nifty_pascal-windows

    # Currently, the anchore scan action does not work on Windows images. Windows scanning is a also a premium-only feature for Anchore.
    # - id: anchore-scan
    #   name: Run Anchore Scan
    #   uses: anchore/scan-action@v3
    #   with:
    #     image: '76eddge/build-images:nifty_pascal-windows'

    # - name: Upload Anchore Scan Report
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: ${{ steps.anchore-scan.outputs.sarif }}

    - name: Login to DockerHub
      if: github.event_name == 'release'
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: github.event_name == 'release'
      run: docker push -a 76eddge/build-images
