name: Build

on:
  push:
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Build Docker Images
      run: ./build.sh
      env:
        DOCKER_BUILDKIT: 1

    - name: Login to DockerHub
      if: startsWith(github.ref, 'refs/tags/')
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username 76eddge --password-stdin

    - name: Push Docker Images
      if: startsWith(github.ref, 'refs/tags/')
      run: ./build.sh --push
      env:
        DOCKER_BUILDKIT: 1
