name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1.3.0
      with:
        version: latest

    - name: Build Docker Images
      run: ./build.sh

